### ISSUE TITLE
[FIX] 각종 버그 수정

### ISSUE THREAD

**Issue by JYPjoy** [DeveloperAcademy-POSTECH/MacC-Team5-COMBINE#109]
## 🗂️ 관련 Issue ID
| 노션 ID | DEV |화면 ID| 해당 없음 |
|:-------:|:-------:|:-------:|:-------:| 

<br/>

## ✅ TO - DO
- [x] STT 화면 지난 후 앱 전체의 오디오 꺼지는 문제 해결
- [x] CoreMotion 사용 후 해제 안 되는 문제 해결 
- [x] UI 수정
- [x] 맞춤법 수정

**Comment by nss321** [comment]
오디오 이슈 해결 완 :)
