### ISSUE TITLE
[REFACTOR] 떡꼬치 화면 UI 리팩토링

### ISSUE THREAD

**Issue by JYPjoy** [DeveloperAcademy-POSTECH/MacC-Team5-COMBINE#43]
## 🗂️ 관련 Issue ID
| 노션 ID | DEV24 |화면 ID| Story_01_Quiz1 |
|:-------:|:-------:|:-------:|:-------:| 

<br/>

## ✅ TO - DO
- [x] 문구 바꾸기 
- [x] 보이스오버 기능 체크
     - [x] 문구 바꾸기
     - [x] 순서 따로 조정하기 
- [x] 오답시 추가 효과 구현: 화면 흔들리는 효과 구현
- [x] 로직 분리
- [x] CollectionView 간격 조정

**Comment by nss321** [comment]
조이 이거 작업하실 때 떡 블록이랑 컨테이너 좌우 여백 좀 주시는게 좋을거 같아용

**Comment by JYPjoy** [comment]
> 조이 이거 작업하실 때 떡 블록이랑 컨테이너 좌우 여백 좀 주시는게 좋을거 같아용

@nss321 
이거 디자이너님들이 여백 주면 스크롤 했을 때 떡 잘려 보인다고 하셔서 UI 수정된 사항 반영한 거예용
원래는 여백 있던 거 삭제했어요.
수정된 UI에서는 떡 블록이랑 컨테이너 좌우 여백 없어용!
