### ISSUE TITLE
[FIX] 떡 주는 뷰에서 다음 뷰로 넘어가지 않는 에러 수정

### ISSUE THREAD

**Issue by dtd1232** [DeveloperAcademy-POSTECH/MacC-Team5-COMBINE#64]
## 🗂️ 관련 Issue ID
| 노션 ID | DEV1 |화면 ID| Story_01 |
|:-------:|:-------:|:-------:|:-------:| 

<br/>

## ✅ TO - DO
- [ ] 뷰 이동 코드 수정

**Comment by nss321** [comment]
제가 이관 받았습니다.
